### ISSUE TITLE
How can I make sure How many GPU cores in GC1000 revision 5037

### ISSUE THREAD

**Issue by suijingfeng** [etnaviv/etna_viv#18]
Loongson 7A1000 north bridge has a vivante GC1000 gpu,  its revision is 5037
loongson 2k1000 soc also have vivante gpu integrated, which lacking kernel etnaviv support

when modprobe etnaviv, the dmesg show that  
 
```
[11147.191406] etnaviv 0000:00:06.0: Device 14:7a15, irq 93
[11147.195312] etnaviv 0000:00:06.0: model: GC1000, revision: 5037
[11147.199218] [drm] Initialized etnaviv 1.2.0 20151214 for 0000:00:06.0 on minor 1
```

so does this meaning that GC1000 does't have a 2D engine ?

Does it have a 2D core in the GC1000 , does it have a GC320 , GC300 or GC200 inside it ?

the gc1000 on our platform is a PCI device， i build etnaviv a module on default，
i have to modprobe it manually(otherwise /dev/dri/renderD128 doesn't show),  
don't know how to make it  auto-registed by the kernel

**Comment by austriancoder** [comment]
This is not how it works. You need to specify your etnaviv GPU cores in a devicetree.
For instance, see what is done in imx6: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/boot/dts/imx6qdl.dtsi?h=v5.8-rc2#n219

**Comment by suijingfeng** [comment]
@austriancoder , thanks your for reply, I am not a kernel developer, when using xf86-video-armada on mips (loongson 3A3000) platform, the GPU hung and recover repeatedly, I dont know where to report it and can i debug this.

the log is append as follows,  I guess the  2d acceleration may have bug, please help !


```
[   35.902343] etnaviv 0000:00:06.0: MMU fault status 0x00000002
[   35.906250] etnaviv 0000:00:06.0: MMU 0 fault addr 0x00875000
[   36.960937] etnaviv 0000:00:06.0: recover hung GPU!

[   36.964843] ------------[ cut here ]------------
[   36.968750] WARNING: CPU: 2 PID: 2244 at include/linux/dma-fence.h:533 drm_sched_resubmit_jobs+0x208/0x228
[   36.976562] Modules linked in: fuse xt_MASQUERADE tun bridge stp llc xt_tcpudp ipt_REJECT nf_reject_ipv4 rfkill xt_conntrack ebtable_nat ebtable_broute ebtable_filter ebtables iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 iptable_mangle iptable_raw iptable_filter dm_mirror dm_region_hash dm_log ip_tables x_tables
[   37.003906] CPU: 2 PID: 2244 Comm: kworker/2:2 Not tainted 5.4.17+ #10
[   37.003906] Workqueue: events drm_sched_job_timedout
[   37.003906] Stack : 98000005f4da3b58 ffffffff802a11a0 ffffffffd500cce0 98000005f4da3ab8
[   37.003906]         c80a33d88f0f11b6 0000000000000000 0000000000000000 ffffffff81fd8b80
[   37.003906]         ffffffff808bd4d8 0000000000000210 0000000000000000 0000000000000002
[   37.003906]         ffffffff81fd89f8 0000000000000002 0000000005f5e100 000000000000020f
[   37.003906]         0000000000000001 ffffffff81fd0000 0000000000000000 0000000000000000
[   37.003906]         ffffffff81ebc738 ffffffffffffff62 0000000000000000 98000005fe466a48
[   37.003906]         98000005fec57240 000000000000000f ffffffff808bc7a0 0000000000000010
[   37.003906]         ffffffff821b0010 98000005f4da0000 98000005f4da3ab0 98000005fe4668f0
[   37.003906]         ffffffff811f836c 0000000000000000 700073746e657665 6666655f7265776f
[   37.003906]         0000746e65696369 c80a33d88f0f11b6 ffffffff80217558 c80a33d88f0f11b6
[   37.003906]         ...
[   37.003906] Call Trace:
[   37.003906] [] show_stack+0x40/0x130
[   37.003906] [] dump_stack+0xac/0xe0
[   37.003906] [] __warn+0xc0/0xe8
[   37.003906] [] warn_slowpath_fmt+0x74/0xc8
[   37.003906] [] drm_sched_resubmit_jobs+0x208/0x228
[   37.003906] [] etnaviv_sched_timedout_job+0xcc/0x108
[   37.003906] [] drm_sched_job_timedout+0x4c/0xb0
[   37.003906] [] process_one_work+0x228/0x468
[   37.003906] [] worker_thread+0x178/0x5b0
[   37.003906] [] kthread+0x11c/0x150
[   37.003906] [] ret_from_kernel_thread+0x14/0x1c
[   37.148437] ---[ end trace 2545d149abd95b50 ]---
[   37.503906] etnaviv 0000:00:06.0: MMU fault status 0x00000001
[   37.507812] etnaviv 0000:00:06.0: MMU 0 fault addr 0x01865fc0
[   37.746093] libaes: exports duplicate symbol aes_decrypt (owned by kernel)
[   38.554687] etnaviv 0000:00:06.0: recover hung GPU!
[   38.558593] ------------[ cut here ]------------
[   38.562500] WARNING: CPU: 2 PID: 2244 at include/linux/dma-fence.h:533 drm_sched_resubmit_jobs+0x208/0x228
[   38.570312] Modules linked in: fuse xt_MASQUERADE tun bridge stp llc xt_tcpudp ipt_REJECT nf_reject_ipv4 rfkill xt_conntrack ebtable_nat ebtable_broute ebtable_filter ebtables iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 iptable_mangle iptable_raw iptable_filter dm_mirror dm_region_hash dm_log ip_tables x_tables
[   38.597656] CPU: 2 PID: 2244 Comm: kworker/2:2 Tainted: G        W         5.4.17+ #10
[   38.597656] Workqueue: events drm_sched_job_timedout
[   38.597656] Stack : 98000005f4da3b58 ffffffff802a11a0 ffffffffd500cce0 98000005f4da3ab8
[   38.597656]         c80a33d88f0f11b6 0000000000000000 0000000000000000 ffffffff81fd8b80
[   38.597656]         ffffffff808bd4d8 0000000000000231 0000000000000000 0000000000000002
[   38.597656]         ffffffff81fd89f8 0000000000000002 0000000005f5e100 0000000000000230
[   38.597656]         0000000000000001 ffffffff81fd0000 0000000000000000 0000000000000000
[   38.597656]         ffffffff81ebc738 ffffffffffffff62 0000000000000000 98000005fe466a48
[   38.597656]         98000005fec57780 000000000000000f ffffffff808bc7a0 0000000000000010
[   38.597656]         ffffffff821b0010 98000005f4da0000 98000005f4da3ab0 98000005fe4668f0
[   38.597656]         ffffffff811f836c 0000000000000000 700073746e657665 6666650071775f75
[   38.597656]         0000746e65696369 c80a33d88f0f11b6 ffffffff80217558 c80a33d88f0f11b6
[   38.597656]         ...
[   38.597656] Call Trace:
[   38.597656] [] show_stack+0x40/0x130
[   38.597656] [] dump_stack+0xac/0xe0
[   38.597656] [] __warn+0xc0/0xe8
[   38.597656] [] warn_slowpath_fmt+0x74/0xc8
[   38.699218] [] drm_sched_resubmit_jobs+0x208/0x228
[   38.699218] [] etnaviv_sched_timedout_job+0xcc/0x108
[   38.714843] [] drm_sched_job_timedout+0x4c/0xb0
[   38.718750] [] process_one_work+0x228/0x468
[   38.718750] [] worker_thread+0x178/0x5b0
[   38.718750] [] kthread+0x11c/0x150
[   38.718750] [] ret_from_kernel_thread+0x14/0x1c
[   38.742187] ---[ end trace 2545d149abd95b51 ]---
[   38.941406] etnaviv 0000:00:06.0: MMU fault status 0x00000002
[   38.949218] etnaviv 0000:00:06.0: MMU 0 fault addr 0x01909100
[   39.996093] etnaviv 0000:00:06.0: recover hung GPU!
[   40.000000] ------------[ cut here ]------------
[   40.003906] WARNING: CPU: 2 PID: 2244 at include/linux/dma-fence.h:533 drm_sched_resubmit_jobs+0x208/0x228
[   40.011718] Modules linked in: fuse xt_MASQUERADE tun bridge stp llc xt_tcpudp ipt_REJECT nf_reject_ipv4 rfkill xt_conntrack ebtable_nat ebtable_broute ebtable_filter ebtables iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 iptable_mangle iptable_raw iptable_filter dm_mirror dm_region_hash dm_log ip_tables x_tables
[   40.039062] CPU: 2 PID: 2244 Comm: kworker/2:2 Tainted: G        W         5.4.17+ #10
[   40.046875] Workqueue: events drm_sched_job_timedout
[   40.050781] Stack : 98000005f4da3b58 ffffffff802a11a0 ffffffffd500cce0 98000005f4da3ab8
[   40.058593]         c80a33d88f0f11b6 0000000000000000 0000000000000000 ffffffff81fd8b80
[   40.066406]         ffffffff808bd4d8 0000000000000251 0000000000000000 0000000000000002
[   40.070312]         ffffffff81fd89f8 0000000000000002 0000000005f5e100 0000000000000250
[   40.078125]         0000000000000001 ffffffff81fd0000 0000000000000000 0000000000000000
[   40.085937]         ffffffff81ebc738 ffffffffffffff62 0000000000000000 98000005fe466a48
[   40.093750]         98000005fec57300 000000000000000f ffffffff808bc7a0 0000000028066798
[   40.101562]         ffffffff821b0010 98000005f4da0000 98000005f4da3ab0 98000005fe4668f0
[   40.109375]         ffffffff811f836c 0000000000000000 700073746e657665 6666655f7265776f
[   40.117187]         0000746e65696369 c80a33d88f0f11b6 ffffffff80217558 c80a33d88f0f11b6
[   40.125000]         ...
[   40.125000] Call Trace:
[   40.128906] [] show_stack+0x40/0x130
[   40.132812] [] dump_stack+0xac/0xe0
[   40.136718] [] __warn+0xc0/0xe8
[   40.140625] [] warn_slowpath_fmt+0x74/0xc8
[   40.144531] [] drm_sched_resubmit_jobs+0x208/0x228
[   40.152343] [] etnaviv_sched_timedout_job+0xcc/0x108
[   40.156250] [] drm_sched_job_timedout+0x4c/0xb0
[   40.164062] [] process_one_work+0x228/0x468
[   40.167968] [] worker_thread+0x178/0x5b0
[   40.171875] [] kthread+0x11c/0x150
[   40.179687] [] ret_from_kernel_thread+0x14/0x1c
[   40.183593] ---[ end trace 2545d149abd95b52 ]---
[   40.359375] etnaviv 0000:00:06.0: MMU fault status 0x00000002
[   40.359375] etnaviv 0000:00:06.0: MMU 0 fault addr 0x0090e9c0
[   41.898437] etnaviv 0000:00:06.0: recover hung GPU!
[   41.902343] ------------[ cut here ]------------
```

**Comment by suijingfeng** [comment]
I am using this kernel: https://github.com/ProgramingOnLoongson/linux/tree/master/drivers/gpu/drm/etnaviv

it is patched by Chen Huacai in order to make it work on mips64el arch,

https://github.com/ProgramingOnLoongson/linux/commit/71d40c0dfa5a38e8f466179b63bc6c9fd096f63c

Can you give some code review please? @austriancoder

**Comment by austriancoder** [comment]
GC1000 0x5037 has 2D and 3D feature bits set --> there will be one driver instance which supports 2D and 3D pipes - nice.

From a very quick look the patch to add pci support to etnaviv looks sane. Are there any plans to upstream this pci driver support?

To debug this issue you need to enable dev coredump support in the kernel and make and install this: https://github.com/etnaviv/etna-gpu-tools

If such a fault will happen this will trigger a dev coredump and in the end you will get the used cmd stream and the buffers. With this information it is possible to debug this issue.

**Comment by suijingfeng** [comment]
thanks you, has take full time to do my own job...,there are a lot of things to learn ...

**Comment by FlyGoat** [comment]
Display Controller driver needs some extra work to be upstreamed.
Etnaviv part looks fine. But we need to deal with black screen issue on glamor.

For context:

https://lists.x.org/archives/xorg-devel/2018-March/056192.html
https://lists.x.org/archives/xorg-devel/2019-July/058239.html

**Comment by suijingfeng** [comment]
@FlyGoat 
I have write a DDX driver base on xf86-video-armsoc, 
which works without 2d hardware acceleration, it is basically modesetting + Fake EXA (software exa),
see https://github.com/ProgramingOnLoongson/xf86-video-loongson7a
can run glmark2-es2 and play Quake 3 arena .

**Comment by FlyGoat** [comment]
@suijingfeng 

Thanks for your info.
But for further development, I think it is necessary to make glamor work. Otherwise, XWayland and generic modesetting driver won't work properly.

@austriancoder 

Have you tried to run glamor with etnaviv? I've seen some identical issue report on I.MX platform but also some success reports.
It is tiled scan-out buffer related. I'm going to try Michel's solution on list[1] soon.
I was lacking too much graphic knowledge years ago thus failed to follow his instruction.
[1]: https://lists.x.org/archives/xorg-devel/2019-July/058239.html

Thanks.

**Comment by austriancoder** [comment]
@FlyGoat 

glamor is broken and is challenging to fix caused by synchronisation issues. unfortunately Xwl + FBO is one of those things we just don't really have a good answer for - X11 wants to bash things directly into the active frontbuffer at random times, Wayland wants you to use separate buffers, etnaviv wants strong end-of-frame markers so it can do copies between render target + texture source.

Here is an other hack you could try:
```
diff --git a/glamor/glamor_render.c b/glamor/glamor_render.c
index be0741a..93c27ae 100644
--- a/glamor/glamor_render.c
+++ b/glamor/glamor_render.c
@@ -1584,6 +1584,16 @@ glamor_composite_clipped_region(CARD8 op,
     if (prect != rect)
         free(prect);
  out:
+
+    if (ok) {
+        glamor_pixmap_fbo        *fbo = glamor_pixmap_fbo_at(dest_pixmap_priv, 0);
+        const struct glamor_format *f = glamor_format_for_pixmap(dest_pixmap);
+        uint8_t buf[16];
+        glPixelStorei(GL_PACK_ALIGNMENT, 4);
+        glBindFramebuffer(GL_FRAMEBUFFER, fbo->fb);
+        glReadPixels(0,0,1,1,f->format,f->type,buf);
+    }
+
     if (temp_src != source)
         FreePicture(temp_src, 0);
     if (temp_mask != mask)

````

**Comment by suijingfeng** [comment]
glamor on our environment(mesa-18.3.4 + libdrm-2.4.97+xserver-1.20.4) just can't even pass the initial stage.

GC1000 v5037 gl version is only OpenGL1.4, so :


```
160 [ 63988.707] (II) Loading /usr/lib64/xorg/modules/libfb.so
161 [ 63988.709] (II) Module fb: vendor="X.Org Foundation"
162 [ 63988.709] -··compiled for 1.20.4, module version = 1.0.0
163 [ 63988.709] -··ABI class: X.Org ANSI C Emulation, version 0.4
164 [ 63988.709] (II) UnloadModule: "fbdev"
165 [ 63988.709] (II) Unloading fbdev
166 [ 63988.709] (II) UnloadSubModule: "fbdevhw"
167 [ 63988.709] (II) Unloading fbdevhw
168 [ 63988.713] Require OpenGL version 2.1 or later. 
169 [ 63988.713] (EE) modeset(0): Failed to initialize glamor at ScreenInit() time.
170 [ 63988.713] (EE)
171 Fatal server error:
172 [ 63988.713] (EE) AddScreen/ScreenInit failed for driver 0
173 [ 63988.713] (EE)
174 [ 63988.713] (EE)
175 Please consult the The X.Org Foundation support
176 -··· at http://wiki.x.org
177  for help.⎵
178 [ 63988.713] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
179 [ 63988.713] (EE)
180 [ 63988.739] (EE) Server terminated with error (1). Closing log file.
```

**Comment by FlyGoat** [comment]
@suijingfeng That have been fixed in latest glamor. It will fallback to GL ES 2.0 of GL 2.1 is not avilable.
Looks like you're using an ancient distro:-(

**Comment by suijingfeng** [comment]
I backport that patch that force glamor using gles2, but still get drakscreen

glamor dark screen is because because GC1000 lack of ARB_texture_swizzle:

```
[  5301.991] glamor_upload_picture_to_texture:    Couldn't upload temporary picture due to missing GL_ARB_texture_swizzle.
[  5301.991]   glamor_composite_choose_shader:    Failed to upload source texture.
[  5301.991]     glamor_composite_with_shader:    glamor_composite_choose_shader failed
[  5301.991]                 glamor_composite:    from picts 0xaab2d634c0:0xaab2af8fa0 1920x1080 / (nil):(nil) 0 x 0 (m, )  to pict 0xaab2ab8810:0xaab2d61040 346x167 (f)
[  5301.991] glamor_upload_picture_to_texture:    Couldn't upload temporary picture due to missing GL_ARB_texture_swizzle.
[  5301.991]   glamor_composite_choose_shader:    Failed to upload source texture.
[  5301.991]     glamor_composite_with_shader:    glamor_composite_choose_shader failed
[  5301.991]                 glamor_composite:    from picts 0xaab2d634c0:0xaab2cff730 80x80 / (nil):(nil) 0 x 0 (m, )  to pict 0xaab2ab8810:0xaab2d61040 346x167 (f)
```

**Comment by suijingfeng** [comment]
even glamor is not broken, we still can get good performance on GC1000.

because GC1000 is so weak,  it is impossible to hold the pressure of 2D acceleration and 3D acceleration at the same time.

run glmark2-es2 score is only 130 in fedora, on UOS, it got 99. 

UOS 's desktop effect get accelerated, but slow. so sad .

**Comment by FlyGoat** [comment]
@suijingfeng 
I do remember can galmor works with both OpenGL mode (after manually skip version check, as the only lacking feature in for GC1000 to support 2.1 is occlusion query), and OpenGL ES mode last June.

I'm not sure what blocks you here.

Yeah, but as XWayland can't stand without glamor, and the future belongs to wayland, I'd still think galmor is important.

**Comment by suijingfeng** [comment]
thanks for help!
